export const FETCH_USERS = 'FETCH_USERS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const UNAUTHENTICATED = 'unauthenticated_user'
export const USER_LOGGEDIN = 'USER_LOGGEDIN'
export const USER_TYPING = 'USER_TYPING'
export const SEND_MESSAGE = 'SEND_MESSAGE'
